# Generated by Django 5.0.1 on 2024-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('legenda', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
