# Generated by Django 5.0.1 on 2024-02-13 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_photography_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
