# Generated by Django 5.0.1 on 2024-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_photography_delete_fotografia"),
    ]

    operations = [
        migrations.AddField(
            model_name="photography",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEBULA", "Nebulosa"),
                    ("STAR", "Estrela"),
                    ("GALAXY", "Galáxia"),
                    ("PLANET", "Planeta"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
