# Generated by Django 5.0.1 on 2024-02-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_alter_photography_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="photography",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
