# Generated by Django 5.0.1 on 2024-02-13 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_photography_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photography",
            name="release_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
