# Generated by Django 5.0.1 on 2024-02-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_photography_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='address',
            field=models.ImageField(blank=True, upload_to='photographs/%Y/%m'),
        ),
    ]
