# Generated by Django 5.0.1 on 2024-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_photography_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
